### PR TITLE
adding a stupid site

### PR DESCRIPTION
**Pull request by pidgezero-one**
this is just a html page on my github.io site that i made as an inside joke in the speedrunning community but i think it fits the spirit of makefrontendshitagain.party

### CODE REVIEW

**Comment by SaraVieira** [comment]
Beautiful! What games do you run?

**Comment by pidgezero-one** [comment]
Mostly Super Mario RPG, but SMRPG runners and Donkey Kong Country runners have a lot of friendship overlap, so this meme mostly circulated around DKC streams. Thank you for merging!!

**Comment by SaraVieira** [comment]
You are super welcome! A lot of respect for speedrunners!

Random question: How do you feel about the new super mario RPG?

**Comment by pidgezero-one** [comment]
Thanks! And I really like it! I think it's a wonderfully well-done and faithful remake. The original is still my favourite, but if the original game is a 10/10 for me, then the remake is a 9.5/10. Did you play it as well?

**Comment by SaraVieira** [comment]
Yes! On my way to finish the remaster now!

**Pull request merged**
