### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by gomesalexandre**

### CODE REVIEW

**Comment by SaraVieira** [comment]
I thought you were portuguese, I am confusion

**Comment by gomesalexandre** [comment]
@SaraVieira Ethnically am, but I'm born and raised in France ! Comprendo e falo portugues um poco  🤟

**Comment by SaraVieira** [comment]
WOW! Nice! I thought so because if your name :)

Btw: deployed: https://makefrontendshitagain.party/ 🎉

**Comment by SaraVieira** [comment]
btw can I have your twitter handle ?

**Comment by SaraVieira** [comment]
nvm found you 🎉

**Comment by gomesalexandre** [comment]
Haha classic !! At least this time someone got the name right, usually it goes like "Are you Spanish ?" and I have to explain that I'm no "Gomez" 🤦

**Comment by SaraVieira** [comment]
I probably only assumed correctly because I am portuguese 😂

**Pull request merged**
