### PR TITLE
Minor Fixes 🕵️

### PR DESCRIPTION
**Pull request by sudovijay**
Sorry for creating multiple PR's, my bad 🤦‍♂️

### CODE REVIEW

**Comment by SaraVieira** [comment]
Awesome!!

Mind running yarn test - - fix?

**Comment by SaraVieira** [comment]
Awesome! Thank you so much!! 👌

**Comment by sudovijay** [comment]
Nothin awesome! here, its all dumb, stick with that 🙃

**Comment by SaraVieira** [comment]
Dumb things can be awesome!

**Pull request merged**
